language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"

sudo: required

os:
  - linux
  - osx

before_script:
  - git clone -b cmake git@github.com:insomniacslk/dublin-traceroute.git
  - cd dublin-traceroute
  - mkdir build
  - cd build
  - cmake ..
  - make
  - sudo make install

script:
  - mkdir build
  - cd build
  - cmake ..
  - make VERBOSE=1


after_script:
  - python -m dublintraceroute --help
